language: php

php:
  - 5.6
  - hhvm
  - 7.0

install:
  - $NPM install -g web-push-testing-service

before_install:
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`)
  - source ~/.nvm/nvm.sh
  - nvm install stable
  - export NODE=$(nvm which stable)
  - export NPM=${NODE%node}npm

before_script:
  - composer install --prefer-source -n --no-dev

script:
  - phpunit -c phpunit.travis.xml
