language: php

php:
  - 5.6
  - hhvm
  - 7.0

install:
  - npm cache clear --force
  - npm install -g n && n stable
  - npm install -g web-push-testing-service

before_script:
  - composer install --prefer-source -n --no-dev

script:
  - phpunit -c phpunit.travis.xml
